CREATE TABLE IF NOT EXISTS cards (
    id SERIAL PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    encrypted_data TEXT NOT NULL,
    hmac TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);