server:
  port: 8080

jwt:
  secret: "supersecretjwtkey"

encryption:
  secret: "32-byte-aes-encryption-key!!!"
  hmac_key: "hmac_key_here"

database:
  host: localhost
  port: 5432
  user: bank_app_user
  password: secure_password
  dbname: bank_db
  sslmode: disable
  migrations_path: file://migrations